name: Dependency updates

on:
  workflow_dispatch:
  schedule:
    # Bump dep.stargate.version regularly, but not too often. Every time dep.stargate.version is changed, engineers
    # will have to download pretty sizable images used for testing.
    - cron: '0 4 * * 1' # 6am UTC+2 on Monday

permissions:
  contents: write
  pull-requests: write

env:
  # credentials for the private repository
  mavenReleaseUsername: ${{ secrets.CODE_ARTIFACT_USERNAME }}
  mavenReleasePassword: ${{ secrets.CODE_ARTIFACT_PASSWORD }}
  mavenSnapshotsUsername: ${{ secrets.CODE_ARTIFACT_USERNAME }}
  mavenSnapshotsPassword: ${{ secrets.CODE_ARTIFACT_PASSWORD }}
  # allow overriding Maven command
  MAVEN: "./mvnw -s .github/settings.xml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          cache: false
          download_dependencies: false
      - name: Update POM properties
        run: |
          $MAVEN versions:update-properties -Dincludes=io.starburst.stargate:\*:\*:\*:\* -pl ':trino-root'
      - name: Generate token
        id: generate_token
        # fork of tibdex/github-app-token
        uses: trinodb/github-actions/github-app-token@2c3f458fcad343199d0e92badaaa6e9dd7993b2e
        with:
          app_id: ${{ vars.TOKEN_GENERATOR_APP_ID }}
          private_key: ${{ secrets.TOKEN_GENERATOR_PRIVATE_KEY }}
      - name: Create Pull Request
        # pin to 4.2.4
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54
        with:
          token: ${{ steps.generate_token.outputs.token }}
          title: 'Update Stargate version'
          commit-message: 'Update Stargate version'
          author: starburst-automation <starburst-automation@users.noreply.github.com>
          committer: starburst-automation <starburst-automation@users.noreply.github.com>
          branch: 'update-stargate'
          delete-branch: true
          team-reviewers: galaxy-trino-maintainers
